Areas/AdminPanel/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsWebsite.Models;


namespace NewsWebsite.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles="Admin,Moderator")]
    public class CategoriesController : Controller
    {
        private readonly NewsContext _context;

        public CategoriesController(NewsContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Category category)
        {
            ModelState.Remove("Id");
            ModelState.Remove("News");
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Category category)
        {
            ModelState.Remove("Id");
            ModelState.Remove("News");

            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'NewsContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Mega News Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="~/assets/js/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Mega News - v4.7.0
  * Template URL: https://bootstrapmade.com/Mega News-free-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
      <div class="align-items-center d-none d-md-flex">
        <i class="bi bi-clock"></i> @DateTime.Now.ToString("dd-MM-yyyy hh:mm")
      </div>
      <div class="d-flex align-items-center">
        <i class="bi bi-phone"></i> Call us now +1 55689 55488 55
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <a href="/Home/Index" class="logo me-auto"><i class="bi bi-house"></i></a>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <h1 class="logo me-auto"><a href="index.html">Mega News</a></h1> -->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto" asp-action="Index">Home</a></li>
          <li><a class="nav-link scrollto" asp-action="TeamMembers" >Team Members</a></li>
          <li><a class="nav-link scrollto" asp-action="ContactUs">Contact US</a></li>
          <li><a class="nav-link scrollto" asp-action="Reviews">Reviews</a></li>
          <li><a class="nav-link scrollto" asp-area="AdminPanel" asp-controller="Categories" asp-action="Index" >AdminPanel</a></li>
          <partial name="_LoginPartial.cshtml"/>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>

      </nav><!-- .navbar -->
      
    </div>
  </header><!-- End Header -->
<section id="hero">
    <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active" style="background-image: url(/assets/img/slide/news.png)">
          <div class="container">
            <h2>Welcome to <span>Mega News</span></h2>
            <p>A website to find out the latest news in all fields around the clock and we care about credibility and accurate details.</p>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item" style="background-image: url(/assets/img/slide/news1.png)">
          <div class="container">
            <h2>Mega News</h2>
            <p>A website to find out the latest news in all fields around the clock and we care about credibility and accurate details.</p>           
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item" style="background-image: url(/assets/img/slide/news3.png)">
          <div class="container">
            <h2>Mega News</h2>
            <p>A site to find out the latest news in all fields around the clock and we care about credibility and accurate details..</p>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
      </a>

    </div>
  </section><!-- End Hero -->

 @RenderBody()
  

  <!-- ======= Footer ======= -->

  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <center>
              <div class="col-lg-3 col-md-6">
                <div class="footer-info">
                  <h3>Mega News</h3>
                  <p>
                    A108 Adam Street <br>
                    NY 535022, USA<br><br>
                    <strong>Phone:</strong> +1 56389 55488 55<br>
                    <strong>Email:</strong> info@example.com<br>
                  </p>
                  <div class="social-links mt-3">
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                  </div>
                </div>
              </div>
          </center>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Mega News</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/purecounter/purecounter.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>
    @RenderSection("Scripts",required:false)
</html>