Areas/AdminPanel/Controllers/TeamMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsWebsite.Data;
using NewsWebsite.Models;
using NewsWebsite.ViewModels;

namespace NewsWebsite.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles="Admin,Moderator")]
    public class TeamMembersController : Controller
    {
        private readonly NewsContext _context;
        private readonly IWebHostEnvironment _host;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public TeamMembersController(NewsContext context, IWebHostEnvironment host,UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _host = host;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: TeamMembers
        public async Task<IActionResult> Index()
        {
            return View(await _context.TeamMembers.ToListAsync());
        }

        // GET: TeamMembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TeamMembers == null)
            {
                return NotFound();
            }

            var teamMember = await _context.TeamMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamMember == null)
            {
                return NotFound();
            }

            return View(teamMember);
        }

        // GET: TeamMembers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TeamMembers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeamMember teamMember)
        {
            ModelState.Remove("Image");
            if (ModelState.IsValid)
            {
                UploadPhoto(teamMember);
                _context.Add(teamMember);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teamMember);
        }

        // GET: TeamMembers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TeamMembers == null)
            {
                return NotFound();
            }

            var teamMember = await _context.TeamMembers.FindAsync(id);
            if (teamMember == null)
            {
                return NotFound();
            }
            return View(teamMember);
        }

        // POST: TeamMembers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TeamMember teamMember)
        {

            ModelState.Remove("Image");
            if (id != teamMember.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    UploadPhoto(teamMember);
                    _context.Update(teamMember);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamMemberExists(teamMember.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teamMember);
        }

        // GET: TeamMembers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TeamMembers == null)
            {
                return NotFound();
            }

            var teamMember = await _context.TeamMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamMember == null)
            {
                return NotFound();
            }

            return View(teamMember);
        }

        // POST: TeamMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TeamMembers == null)
            {
                return Problem("Entity set 'NewsContext.TeamMembers'  is null.");
            }
            var teamMember = await _context.TeamMembers.FindAsync(id);
            if (teamMember != null)
            {
                _context.TeamMembers.Remove(teamMember);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Select the user and their roles 
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> UserRoles()
        {
            var users = await _userManager.Users.ToListAsync();
            var roles = await _roleManager.Roles.ToListAsync();
            List<UserRolesVm> userRoles=new List<UserRolesVm>();
            foreach (var user in users)
            {
                var userroles=await _userManager.GetRolesAsync(user);
                userRoles.Add(new UserRolesVm { User = user, Roles = (List<string>)userroles}); 
            }
            ViewBag.Roles = roles;
            return View(userRoles); 

        }

        // Function to upload photos
        public void UploadPhoto(TeamMember member)
        {
            if (member.File != null)
            {
                string FolderPath = Path.Combine(_host.WebRootPath, "Images");
                string UniqueImageName = Guid.NewGuid() + ".jpg";
                string ImagePath = Path.Combine(FolderPath, UniqueImageName);
                using (var filestream = new FileStream(ImagePath, FileMode.Create))
                {
                    member.File.CopyTo(filestream);
                }
                member.Image = UniqueImageName;
            }
        }

        //Add or remove roles from user
        public async Task<IActionResult> AddRemoveRole(string userid,string role)
        {
            var user = await _userManager.FindByIdAsync(userid);
            var result = await _userManager.AddToRoleAsync(user,role);
            if(!result.Succeeded)
                await _userManager.RemoveFromRoleAsync(user, role);
            return RedirectToAction("UserRoles");
        }
        private bool TeamMemberExists(int id)
        {
            return _context.TeamMembers.Any(e => e.Id == id);
        }
    }
}

Areas/AdminPanel/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsWebsite.Data;
using NewsWebsite.ViewModels;
using System.Net.Mail;

namespace NewsWebsite.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // Select all users and their roles
        public IActionResult Index()
        {
            var users = _userManager.Users.Select(user => new UsersVm
            {
                Id=user.Id,
                Name = string.Join(", ", new List<string> { user.FirstName, user.LastName }),
                Email = user.Email,
                UserRoles = _userManager.GetRolesAsync(user).Result
            }).ToList();

            return View(users);
        }

        // Select all roles and return viem model for the view
        public IActionResult Create()
        {
            var roles = _roleManager.Roles.Select(r => new RoleCheckBoxVm 
            {
                RoleName=r.Name
            }).ToList();

            var user = new CreateUserVm
            {
                Roles = roles
            };
            return View(user);
        }

        // Action to create a new user
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserVm model)
        {
            //check for the model
            if(!ModelState.IsValid)
                return View(model);

            //check if the email is already registered
            if(await _userManager.FindByEmailAsync(model.Email)!=null)
            {
                ModelState.AddModelError("Email", "Email address is already registered");
                return View(model);
            }

            //Each user must have at least one role
            if (!model.Roles.Any(r=> r.IsSelected))
            {
                ModelState.AddModelError("Roles", "You must choose at least one role");
                return View(model);
            }

            // Add the user to the database
            var user = new ApplicationUser
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                UserName = new MailAddress(model.Email).User
            };
            var result =await _userManager.CreateAsync(user, model.Password);
            if(!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("Roles", error.Description);
                }
                return View(model);
            }

            // Add Roles to the user
            await _userManager.AddToRolesAsync(user, model.Roles.Select(r => r.RoleName));

            return RedirectToAction(nameof(Index));
        }

        // Select the user with the ID and send it to the view for editing
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            var model = new EditVm
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Roles = _roleManager.Roles.Select(r => new RoleCheckBoxVm
                {
                    RoleName = r.Name,
                    IsSelected = _userManager.IsInRoleAsync(user,r.Name).Result
                }).ToList()
            };

            return View(model);
        }


        // An action to apply changes to the user
        [HttpPost]
        public async Task<IActionResult> Edit(EditVm model)
        {
            if (!ModelState.IsValid)
                return View(model);

            // Check for Id
            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null)
                return NotFound();

            //Check for Email
            var userWithSameEmail = await _userManager.FindByEmailAsync(model.Email);
            if(userWithSameEmail != null && userWithSameEmail.Id != model.Id)
            {
                ModelState.AddModelError("Email", "This Email is already assigned for another user");
                return View(model);
            }

            //Apply changes
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.Email = model.Email;


            // Add or remove roles from user
            var userRoles = await _userManager.GetRolesAsync(user);

            foreach (var role in model.Roles)
            {
                if (userRoles.Any(r => r == role.RoleName) && !role.IsSelected)
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);

                if(!userRoles.Any(r=> r==role.RoleName) && role.IsSelected)
                    await _userManager.AddToRoleAsync(user, role.RoleName);

            }

            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(Index)); 
        }

        // Action for deleting user
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            var result=await _userManager.DeleteAsync(user);
                
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/AdminPanel/Views/shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<!DOCTYPE html>
<html lang="en">

    <head>
        <!-- Required meta tags-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="au theme template">
        <meta name="author" content="Hau Nguyen">
        <meta name="keywords" content="au theme template">

        

        <!-- Fontfaces CSS-->
        <link href="~/AdminPanel/css/font-face.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

        <!-- Bootstrap CSS-->
        <link href="~/AdminPanel/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">
        <link href="~/assets/js/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

        <!-- ~/AdminPanel/vendor CSS-->
        <link href="~/AdminPanel/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/wow/animate.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/slick/slick.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/select2/select2.min.css" rel="stylesheet" media="all">
        <link href="~/AdminPanel/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

        <!-- Main CSS-->
        <link href="~/AdminPanel/css/theme.css" rel="stylesheet" media="all">

    </head>

    <body class="animsition" style="animation-duration: 900ms; opacity: 1;">
            <div class="page-wrapper">
                <!-- HEADER MOBILE-->
                <header class="header-mobile d-block d-lg-none">
                    <div class="header-mobile__bar">
                        <div class="container-fluid">
                            <div class="header-mobile-inner">
                                <a class="logo" href="index.html">
                                    <img src="~/AdminPanel/images/icon/logo.png" alt="CoolAdmin">
                                </a>
                                <button class="hamburger hamburger--slider" type="button">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <nav class="navbar-mobile">
                        <div class="container-fluid">
                            <ul class="navbar-mobile__list list-unstyled">
                                <li>
                                    <a href="/AdminPanel/Categories">
                                        <i class="fas fa-chart-bar"></i>Manage Categories</a>
                                </li>
                                <li>
                                    <a href="/AdminPanel/News">
                                        <i class="fas fa-table"></i>Manage News</a>
                                </li>
                                <li>
                                    <a href="/AdminPanel/TeamMembers">
                                        <i class="far fa-check-square"></i>Manage Team Members</a>
                                </li>
                                <li>
                                    <a asp-controller="TeamMembers" asp-action="UserRoles">
                                        <i class="fas fa-calendar-alt"></i>Manage Roles</a>
                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="Index">
                                        <i class="fas fa-calendar-alt"></i>Manage Users</a>
                                </li>
                                <li>
                                    <a href="Home/Index">
                                        <i class="fas fa-calendar-alt"></i>Website</a>
                                </li>
                                
                                
                            </ul>
                        </div>
                    </nav>
                </header>
                <!-- END HEADER MOBILE-->

                <!-- MENU SIDEBAR-->
                <aside class="menu-sidebar d-none d-lg-block">
                    <div class="logo">
                        <a href="#">
                            <img src="~/AdminPanel/images/icon/logo.png" alt="Cool Admin">
                        </a>
                    </div>
                    <div class="menu-sidebar__content js-scrollbar1 ps">
                        <nav class="navbar-sidebar">
                            <ul class="list-unstyled navbar__list">
                                <li>
                                    <a href="/AdminPanel/Categories">
                                        <i class="fas fa-chart-bar"></i>Manage Categories</a>
                                </li>
                                <li>
                                    <a href="/AdminPanel/News">
                                        <i class="fas fa-table"></i>Manage News</a>
                                </li>
                                <li>
                                    <a href="/AdminPanel/TeamMembers">
                                        <i class="far fa-check-square"></i>Manage Team Members</a>
                                </li>
                                <li>
                                    <a asp-controller="TeamMembers" asp-action="UserRoles">
                                        <i class="fas fa-calendar-alt"></i>Manage Roles</a>
                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="Index">
                                        <i class="fas fa-calendar-alt"></i>Manage Users</a>
                                </li>
                                <li class="has-sub">
                                    <a class="js-arrow" href="/Home/Index">
                                        <i class="fas fa-copy"></i>Website</a>
                                </li>
                            </ul>
                        </nav>
                    <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
                </aside>
                <!-- END MENU SIDEBAR-->

                <!-- PAGE CONTAINER-->
                <div class="page-container">
                    <!-- HEADER DESKTOP-->
                    <header class="header-desktop">
                        <div class="section__content section__content--p30">
                            <div class="container-fluid">
                                <div class="header-wrap d-flex justify-content-end">
                                    <div class="header-button">
                                        <div class="account-wrap ">
                                            <div class="account-item clearfix js-item-menu">
                                                <div class="image">
                                                      <div class="avatar">
                                                        
                                                             <img src="data:image/*;base64,@(Convert.ToBase64String(userManager.GetUserAsync(User).Result.ProfilePicture))" />
                                                        
                                                      </div>
                                                </div>
                                            
                                                <div class="content">
                                                    <a class="js-acc-btn" asp-controller="AdminPanel" asp-action="Index">@userManager.GetUserAsync(User).Result.FirstName</a>
                                                </div>
                                                <div class="account-dropdown js-dropdown">
                                                    <div class="info clearfix">
                                                        <div class="image">
                                                               <img src="data:image/*;base64,@Convert.ToBase64String(userManager.GetUserAsync(User).Result.ProfilePicture)" alt="profile picture">
                                                        </div>
                                                        <div class="content">
                                                            <h5 class="name">
                                                                    @userManager.GetUserAsync(User).Result.FirstName
                                                            </h5>
                                                            <span class="email">
                                                                 @userManager.GetUserAsync(User).Result.Email
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="account-dropdown__body">
                                                        <partial name="_LoginPartial" />
                                                    </div>
                                                    
                                              
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </header>
                    <!-- HEADER DESKTOP-->

                    <!-- MAIN CONTENT-->
                    <div class="main-content">
                            @RenderBody()
                    </div>
                    <!-- END MAIN CONTENT-->
                    <!-- END PAGE CONTAINER-->
                </div>

            </div>

            <!-- Jquery JS-->
            <script src="~/AdminPanel/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/AdminPanel/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/AdminPanel/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- ~/AdminPanel/vendor JS       -->
            <script src="~/AdminPanel/vendor/slick/slick.min.js">
            </script>
            <script src="~/AdminPanel/vendor/wow/wow.min.js"></script>
            <script src="~/AdminPanel/vendor/animsition/animsition.min.js"></script>
            <script src="~/AdminPanel/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
            </script>
            <script src="~/AdminPanel/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/AdminPanel/vendor/counter-up/jquery.counterup.min.js">
            </script>
            <script src="~/AdminPanel/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/AdminPanel/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/AdminPanel/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/AdminPanel/vendor/select2/select2.min.js">
            </script>

            <!-- Main JS-->
            <script src="~/AdminPanel/js/main.js"></script>


    </body>
     @RenderSection("Scripts",required:false)
</html>
<!-- end document-->